<a href="https://colab.research.google.com/github/jugernaut/Prometeo/blob/desarrollo/02_AlgebraLineal/06_Normas/07_NormasInducidas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Normas Inducidas
### Proyecto PAPIME PE101019
- Autor: Miguel Angel Pérez León
- Rev: mar jun  24 17:08:27 CDT 2020

De igual manera como se definió la norma en el espacio de los vectores en $\mathbb{R}^{n}$, en esta sección se procede a definir la norma para el espacio de las matrices $A\in M_{n\times n}$ sobre $\mathbb{R}$.

**Una función** $\left\Vert \cdot\right\Vert$ de matrices, se denomina norma matricial si $\left\Vert \cdot\right\Vert$  si para cualesquiera matrices A,B de nxn se satisfacen las siguientes propiedades.

1.- $\left\Vert A\right\Vert \geq0$.\
2.- $\left\Vert A\right\Vert =0\,\Longleftrightarrow A=0$.\
3.- $\left\Vert \alpha A\right\Vert =\left|\alpha\right|\left\Vert A\right\Vert$.\
4.- $\left\Vert A+B\right\Vert \leq\left\Vert A\right\Vert +\left\Vert B\right\Vert$. (desigualdad triangular)\
5.- $\left\Vert AB\right\Vert \leq\left\Vert A\right\Vert \left\Vert B\right\Vert$ (compatibilidad o consistencia).

¿Conoces alguna función $\left(\left\Vert \cdot\right\Vert \right)$ que cumpla con las propiedades anteriores para el espacio de las matrices de $n\times n$?. 

## Normas Matricial inducida (subordinada)

**Definición** Sea $p\geq1,\:\vec{x}\in\mathbb{R}^{n}$, la p-norma de una matriz $A\in M_{n\times n}$ esta definida por.

$$\left\Vert A\right\Vert _{p}:=\underset{x\neq0}{sup}\frac{\left\Vert A\vec{x}\right\Vert _{p}}{\left\Vert \vec{x}\right\Vert _{p}}$$

Norma matricial inducida por la 1-norma vectorial. 

$$\left\Vert A\right\Vert _{1}\:=\underset{x\neq0}{sup}\frac{\left\Vert A\vec{x}\right\Vert _{1}}{\left\Vert \vec{x}\right\Vert _{1}}\overset{\underbrace{*Teo\,1.}}{=}\underset{1\leq j\leq n}{max}\sum_{i=1}^{n}\left|a_{ij}\right|=\underset{1\leq j\leq n}{max}\left\Vert \vec{a}_{j}\right\Vert _{1}\:(suma\,columnas)$$

Norma matricial inducida por la norma del supremo.

$$\left\Vert A\right\Vert _{\infty}:=\underset{x\neq0}{sup}\frac{\left\Vert A\vec{x}\right\Vert _{\infty}}{\left\Vert \vec{x}\right\Vert _{\infty}}\overset{\underbrace{*Teo\,2.}}{=}\underset{1\leq i\leq n}{max}\sum_{j=1}^{n}\left|a_{ij}\right|=\underset{1\leq i\leq n}{max}\left\Vert \vec{a}_{i}\right\Vert _{\infty}\:(suma\,renglones)$$



## 1-Norma Matricial

Hecho. Recordatorio de álgebra lineal

Hecho. Sea $A=\left(\begin{array}{cc}
a_{11} & a_{12}\\
a_{21} & a_{22}
\end{array}\right)$ y $\vec{x}=\left(\begin{array}{c}
x_{1}\\
x_{2}
\end{array}\right)$ la operación $A\vec{x}$ esta definida como$$A\vec{x}=\left(\begin{array}{c}
a_{11}x_{1}+a_{12}x_{2}\\
a_{21}x_{1}+a_{22}x_{2}
\end{array}\right)=\left(\begin{array}{c}
c_{1}\\
c_{2}
\end{array}\right)$$

De tal manera que cada entrada $c_{i}$ la podemos ver como una sumatoria, es decir

$$\begin{eqnarray*}
c_{1}=\sum_{i=1}^{n} a_{1j}x_{j}\\
c_{2}=\sum_{j=1}^{2} a_{2j}x_{j}\end{eqnarray*}\tag{1}$$






## 1-Norma Matricial

Para poder demostrar que la 1-norma matricial de $A\in M_{n\times n}$ es el máximo de las normas de los vectores columnas es decir, $$\left\Vert A\right\Vert _{1}=\underset{1\leq j\leq n}{max}\left\Vert \vec{a}_{j}\right\Vert _{1}\tag{2}$$

Se necesita considerar lo mostrado en la celda anterior y pensar en la matriz A como una lista de columnas.

Prueba de (2)

Sea $\vec{x}\in\mathbb{R}^{n}$ y $A\in M_{n\times n}$ con $A=\left[\vec{a}_{1}|\vec{a}_{2}\text{|}\cdots\text{|}\vec{a}_{n}\right]$, donde $\vec{a}_{j}$ es un vector columna en $\mathbb{R}^{n}$. Consideremos la bola unitaria en la 1-norma $:=\left\{ \vec{x}\in\mathbb{R}^{n}\mid\left\Vert \vec{x}\right\Vert _{1}=\sum_{j=1}^{n}\left|x_{j}\right|\leq1\right\}$ . Cualquier vector $A\vec{x}$ satisface:

$$\left\Vert A\vec{x}\right\Vert _{1}	\overset{\underbrace{(1)}}{=}	\left\Vert \sum_{j=1}^{n}\vec{a}_{j}x_{j}\right\Vert _{1}\overset{\underbrace{prop\,4\,nor}}{\leq}\sum_{j=1}^{n}\left\Vert \vec{a}_{j}x_{j}\right\Vert _{1}\overset{\underbrace{prop\,3\,nor.}}{=}\sum_{j=1}^{n}\left\Vert \vec{a}_{j}\right\Vert _{1}\left|x_{j}\right|
	\overset{\underbrace{def.max.}}{\leq}	\underset{1\leq j\leq n}{max}\left\Vert \vec{a}_{j}\right\Vert _{1}\sum_{j=1}^{n}\left|x_{j}\right|\overset{\underbrace{bola\,unit.}}{\leq}\underset{1\leq j\leq n}{max}\left\Vert \vec{a}_{j}\right\Vert _{1}
\Longrightarrow	\left\Vert A\vec{x}\right\Vert _{1}	\leq\underset{1\leq j\leq n}{max}\left\Vert \vec{a}_{j}\right\Vert _{1}$$

Prueba. Si elegimos $\vec{x}=\vec{e}_{j}$ (es decir el vector canónico, ademas $\left\Vert \vec{e}_{j}\right\Vert _{1}=1)$ con un 1 en la entrada j. Donde j maximiza, $\left\Vert \vec{a}_{j}\right\Vert _{1}$, obtenemos la cota máxima.$$\therefore\left\Vert A\right\Vert _{1}=\underset{x\neq0}{sup}\frac{\left\Vert A\vec{x}\right\Vert _{1}}{\left\Vert \vec{x}\right\Vert _{1}}=\underset{1\leq j\leq n}{max}\left\Vert \vec{a}_{j}\right\Vert _{1}$$

## Ejemplo 1-norma y del supremo. Sea $$A=\left(\begin{array}{ccc}
3 & -1 & 4\\
-5 & 0 & 2\\
1 & -2 & 6
\end{array}\right)$$

Calcular $\left\Vert A\right\Vert _{1}$ y $\left\Vert A\right\Vert _{\infty}$

In [ ]:
import numpy as np

A = np.array([[3, -1, 4],[-5, 0, 2],[1, -2, 6]])
print (A)

# Calculamos la 1-norma de A
print (np.linalg.norm(A, 1))

# Calculamos la norma del supremo de A
print (np.linalg.norm(A, np.inf))

[[ 3 -1  4]
 [-5  0  2]
 [ 1 -2  6]]
12.0
9.0


## Ejemplo 2-norma o norma espectral

**Definición.** La norma espectral se define de la siguiente manera, sea $A\in M_{n\times n}$ y $\vec{x}\in\mathbb{R}^{n}.\left\Vert A\right\Vert _{2}=\underset{x\neq0}{sup}\frac{\left\Vert A\vec{x}\right\Vert _{2}}{\left\Vert \vec{x}\right\Vert _{2}}$

Aunque también se puede mostrar que. $\left\Vert A\right\Vert _{2}=\sqrt{max\,eigenvalor\,A^{T}A}$

Ejemplo. Sea $$A=\left(\begin{array}{cc}
2 & 5\\
1 & 3
\end{array}\right)$$ Calcular $\left\Vert A\right\Vert _{2}$

• Para encontrar los eigenvalores de A necesitamos calcular $det\left(\left(A^{T}A\right)-\lambda I\right)$.

• Lo primero es calcular la matriz transpuesta de $A$, es decir $$A^{T}=\left(\begin{array}{cc}
2 & 1\\
5 & 3
\end{array}\right)$$

• Ahora es necesario encontrar el producto de $A$ transpuesta por $A$.$$A^{T}A=\left(\begin{array}{cc}
2 & 1\\
5 & 3
\end{array}\right)\left(\begin{array}{cc}
2 & 5\\
1 & 3
\end{array}\right)=\left(\begin{array}{cc}
5 & 13\\
13 & 34
\end{array}\right)$$

• Lo siguiente es calcular el producto anterior menos $lambda-veces$ la identidad.$$A^{T}A-\lambda I=\left(\begin{array}{cc}
5 & 13\\
13 & 34
\end{array}\right)-\left(\begin{array}{cc}
\lambda & 0\\
0 & \lambda
\end{array}\right)=\left(\begin{array}{cc}
5-\lambda & 13\\
13 & 34-\lambda
\end{array}\right)$$

• Finalmente se calcula el determinante de la matriz anterior 
$$\begin{eqnarray*}det\left(\left(A^{T}A\right)-\lambda I\right) =	\left(5-\lambda\right)\left(34-\lambda\right)-\left(13\times13\right) \\
=	170-5\lambda-34\lambda+\lambda^{2}-169 \\
=	\lambda^{2}-39\lambda+1 \end{eqnarray*}$$

• Por lo que al encontrar las raíces de esta ecuación cuadrática, se tiene que$$\begin{cases}
\lambda_{1}=\frac{39+\sqrt{1517}}{2} & =38.97434\\
\lambda_{2}=\frac{39-\sqrt{1517}}{2} & =0.02566
\end{cases}$$

$$\therefore\left\Vert A\right\Vert _{2}=\sqrt{38.97434}=6.24294338$$


In [ ]:
A = np.array([[2, 5],[1, 3]])
print (A)

# Calculamos la 2-norma de A
print (np.linalg.norm(A, 2))

[[2 5]
 [1 3]]
6.2429433838655335


## Referencias

*   Riswan Butt, Numerical Analysys Using Matlab, Jones and Bartlett.
*   Ward Cheney, David Kincaid, Métodos Numéricos y Computación, Cenage Learning.
*   Richard L. Burden, J. Douglas Faires, Análisis Numérico, Math Learning.
*   Yuri N. Skiba, Introducción a los Métodos Numéricos. 