<a href="https://colab.research.google.com/github/jugernaut/Prometeo/blob/desarrollo/02_AlgebraLineal/06_Normas/07_NormasInducidas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Normas Inducidas
### Trabajo realizado con el apoyo del Programa UNAM-DGAPA-PAPIME PE101019
- Autor: Miguel Angel Pérez León
- Rev: mar jun  24 17:08:27 CDT 2020

Este sitio puede ser usado libremente, tanto por profesores como por estudiantes, que deseen complementar sus cursos y conocimientos en los temas antes mencionados. Los materiales están bajo una Licencia Creative Commons Atribución-NoComercial-CompartirIgual 4.0 Internacional

<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Licencia Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />Esta obra está bajo una <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Licencia Creative Commons Atribución-NoComercial-CompartirIgual 4.0 Internacional</a>.

## Introducción

El concepto de norma no se aplica únicamente para vectores, en cualquier espacio vectorial o subespacio es muy útil definir el concepto de norma para poder establecer una forma de medir distancias.

A continuación veremos cómo se define el concepto de norma para el subespacio de las matrices cuadradas.


De igual manera, como se definió la norma en el espacio vectorial $\mathbb{R}^{n}$, en esta sección se procede a definir la norma para el subespacio de las matrices $A\in M_{n\times n}$ sobre $\mathbb{R}$.

**Una función** $\left\Vert \cdot\right\Vert$ de matrices, se denomina norma matricial $\left\Vert \cdot\right\Vert$  si para cualesquiera matrices $A, B \in M_{n\times n}$ sobre $\mathbb{R}$ se satisfacen las siguientes propiedades.

1.- $\left\Vert A\right\Vert \geq0$.

2.- $\left\Vert A\right\Vert =0\,\Longleftrightarrow A=0$.

3.- $\left\Vert \alpha A\right\Vert =\left|\alpha\right|\left\Vert A\right\Vert$.

4.- $\left\Vert A+B\right\Vert \leq\left\Vert A\right\Vert +\left\Vert B\right\Vert$ (desigualdad triangular).

5.- $\left\Vert AB\right\Vert \leq\left\Vert A\right\Vert \left\Vert B\right\Vert$ (compatibilidad o consistencia).

¿Conoces alguna función $\left(\left\Vert \cdot\right\Vert \right)$ que cumpla con las propiedades anteriores para el subespacio de las matrices de $n\times n$?. 

## Normas Matricial inducida (subordinada)

**Definición** Sea $p\geq1,\:\vec{x}\in\mathbb{R}^{n}$, la p-norma de una matriz $A\in M_{n\times n}$ esta definida por.

$$\left\Vert A\right\Vert _{p}:=\underset{\vec{x}\neq\vec{0}}{sup}\frac{\left\Vert A\vec{x}\right\Vert _{p}}{\left\Vert \vec{x}\right\Vert _{p}}$$

Norma matricial inducida por la 1-norma vectorial. 

$$\left\Vert A\right\Vert _{1}\:=\underset{\vec{x}\neq\vec{0}}{sup}\frac{\left\Vert A\vec{x}\right\Vert _{1}}{\left\Vert \vec{x}\right\Vert _{1}}\overset{\underbrace{*Teo\,1.}}{=}\underset{1\leq j\leq n}{max}\sum_{i=1}^{n}\left|a_{ij}\right|=\underset{1\leq j\leq n}{max}\left\Vert \vec{a}_{j}\right\Vert _{1}\:(suma\,columnas)$$

Norma matricial inducida por la norma del supremo.

$$\left\Vert A\right\Vert _{\infty}:=\underset{\vec{x}\neq\vec{0}}{sup}\frac{\left\Vert A\vec{x}\right\Vert _{\infty}}{\left\Vert \vec{x}\right\Vert _{\infty}}\overset{\underbrace{*Teo\,2.}}{=}\underset{1\leq i\leq n}{max}\sum_{j=1}^{n}\left|a_{ij}\right|=\underset{1\leq i\leq n}{max}\left\Vert \vec{a}_{i}\right\Vert _{\infty}\:(suma\,renglones)$$



## 1-Norma Matricial

Recordatorio de álgebra lineal

Sea $A=\left(\begin{array}{cc}
a_{11} & a_{12}\\
a_{21} & a_{22}
\end{array}\right)$ y $\vec{x}=\left(\begin{array}{c}
x_{1}\\
x_{2}
\end{array}\right)$, la operación $A\vec{x}$ esta definida como$$A\vec{x}=\left(\begin{array}{c}
a_{11}x_{1}+a_{12}x_{2}\\
a_{21}x_{1}+a_{22}x_{2}
\end{array}\right)=\left(\begin{array}{c}
a_{11}\\
a_{21}
\end{array}\right)x_{1}+
\left(\begin{array}{c}
a_{12}\\
a_{22}
\end{array}\right)x_{2}
=\left(\begin{array}{c}
c_{1}\\
c_{2}
\end{array}\right) \tag{1}
$$

De tal manera que si pensamos en la matriz $A$ como una lista de vectores columna, el resultado de la operación $A\vec{x}$ es la suma de cada uno de los vectores columna, multiplicados por la correspondiente componente de $\vec{x}$.

Para poder demostrar que la 1-norma matricial de $A\in M_{n\times n}$ sobre $\mathbb{R}$ es el máximo de las normas de los vectores columnas, es decir, $$\left\Vert A\right\Vert _{1}=\underset{1\leq j\leq n}{max}\left\Vert \vec{a}_{j}\right\Vert _{1}\tag{2}$$

Se necesita considerar lo mostrado en (1) y pensar en la matriz $A$ como una lista de columnas.

Prueba de (2)

Sea $\vec{x}\in\mathbb{R}^{n}$ y $A\in M_{n\times n}$ sobre $\mathbb{R}$ con $A=\left[\vec{a}_{1}|\vec{a}_{2}\text{|}\cdots\text{|}\vec{a}_{n}\right]$, donde $\vec{a}_{j}$ es un vector columna en $\mathbb{R}^{n}$. Consideremos la bola unitaria en la 1-norma $:=\left\{ \vec{x}\in\mathbb{R}^{n}\mid\left\Vert \vec{x}\right\Vert _{1}=\sum_{j=1}^{n}\left|x_{j}\right|\leq1\right\}$ . Cualquier vector $A\vec{x}$ satisface:

$$\left\Vert A\vec{x}\right\Vert _{1}	\overset{\underbrace{(1)}}{=}	\left\Vert \sum_{j=1}^{n}\vec{a}_{j}x_{j}\right\Vert _{1}\overset{\underbrace{prop\,4\,nor}}{\leq}\sum_{j=1}^{n}\left\Vert \vec{a}_{j}x_{j}\right\Vert _{1}\overset{\underbrace{prop\,3\,nor.}}{=}\sum_{j=1}^{n}\left\Vert \vec{a}_{j}\right\Vert _{1}\left|x_{j}\right|
	\overset{\underbrace{def.max.}}{\leq}	\underset{1\leq j\leq n}{max}\left\Vert \vec{a}_{j}\right\Vert _{1}\sum_{j=1}^{n}\left|x_{j}\right|\overset{\underbrace{bola\,unit.}}{\leq}\underset{1\leq j\leq n}{max}\left\Vert \vec{a}_{j}\right\Vert _{1}
$$

$$\therefore	\left\Vert A\vec{x}\right\Vert _{1}	\leq\underset{1\leq j\leq n}{max}\left\Vert \vec{a}_{j}\right\Vert _{1}$$

Si elegimos $\vec{x}=\vec{e}_{j}$ (es decir el vector canónico, ademas $\left\Vert \vec{e}_{j}\right\Vert _{1}=1)$ con un 1 en la entrada $j$. Donde $j$ maximiza, $\left\Vert \vec{a}_{j}\right\Vert _{1}$, obtenemos la minima cota superior (en otras palabras el $sup$) y por lo tanto la igualdad.

$$\therefore\left\Vert A\right\Vert _{1}=\underset{\vec{x}\neq\vec{0}}{sup}\frac{\left\Vert A\vec{x}\right\Vert _{1}}{\left\Vert \vec{x}\right\Vert _{1}}=\underset{1\leq j\leq n}{max}\left\Vert \vec{a}_{j}\right\Vert _{1}$$

### Ejemplo

Sea $$A=\left(\begin{array}{ccc}
3 & -1 & 4\\
-5 & 0 & 2\\
1 & -2 & 6
\end{array}\right)$$

Calcular $\left\Vert A\right\Vert _{1}$ y $\left\Vert A\right\Vert _{\infty}$

$\left\Vert A\right\Vert _{1}=\underset{1\leq j\leq n}{max}\left\Vert \vec{a}_{j}\right\Vert _{1}=\underset{1\leq j\leq 3}{max}\left\Vert \vec{a}_{j}\right\Vert _{1}=max\{(3+5+1=9),(1+0+2=3),(4+2+6=12)\}=12$

$\left\Vert A\right\Vert _{\infty}=\underset{1\leq i\leq n}{max}\left\Vert \vec{a}_{i}\right\Vert _{\infty}=\underset{1\leq i\leq 3}{max}\left\Vert \vec{a}_{i}\right\Vert _{\infty}=max\{(3+1+4=8),(5+0+2=7),(1+2+6=9)\}=9$

El resultado se pueden comprobar usando el módulo *linalg* de *numpy*.

In [ ]:
import numpy as np

# Se define la matriz A
A = np.array([[3, -1, 4],[-5, 0, 2],[1, -2, 6]])
print (A)

# Calculamos la 1-norma de A
print (np.linalg.norm(A, 1))

# Calculamos la norma del supremo de A
print (np.linalg.norm(A, np.inf))

[[ 3 -1  4]
 [-5  0  2]
 [ 1 -2  6]]
12.0
9.0


## La 2-norma o norma espectral

**Definición.** La norma espectral se define de la siguiente manera, sea $A\in M_{n\times n}$ sobre $\mathbb{R}^{n}$ y $\vec{x}\in\mathbb{R}^{n}$.

$$\left\Vert A\right\Vert _{2}=\underset{\vec{x}\neq\vec{0}}{sup}\frac{\left\Vert A\vec{x}\right\Vert _{2}}{\left\Vert \vec{x}\right\Vert _{2}}$$

Aunque también se puede mostrar que.

$$\left\Vert A\right\Vert _{2}=\sqrt{max\,eigenvalor\,A^{T}A}$$

### Ejemplo

Sea $$A=\left(\begin{array}{cc}
2 & 5\\
1 & 3
\end{array}\right)$$ Calcular $\left\Vert A\right\Vert _{2}$

• Para encontrar los eigenvalores de A necesitamos calcular $det\left(\left(A^{T}A\right)-\lambda I\right)$.

• Lo primero es calcular la matriz transpuesta de $A$, es decir: $$A^{T}=\left(\begin{array}{cc}
2 & 1\\
5 & 3
\end{array}\right)$$

• Ahora es necesario encontrar el producto de $A$ transpuesta por $A$.$$A^{T}A=\left(\begin{array}{cc}
2 & 1\\
5 & 3
\end{array}\right)\left(\begin{array}{cc}
2 & 5\\
1 & 3
\end{array}\right)=\left(\begin{array}{cc}
5 & 13\\
13 & 34
\end{array}\right)$$

• Lo siguiente es calcular el producto anterior menos $lambda-veces$ la identidad.$$A^{T}A-\lambda I=\left(\begin{array}{cc}
5 & 13\\
13 & 34
\end{array}\right)-\left(\begin{array}{cc}
\lambda & 0\\
0 & \lambda
\end{array}\right)=\left(\begin{array}{cc}
5-\lambda & 13\\
13 & 34-\lambda
\end{array}\right)$$

• Finalmente se calcula el determinante de la matriz anterior 
$$\begin{eqnarray*}det\left(\left(A^{T}A\right)-\lambda I\right) =	\left(5-\lambda\right)\left(34-\lambda\right)-\left(13\times13\right) \\
=	170-5\lambda-34\lambda+\lambda^{2}-169 \\
=	\lambda^{2}-39\lambda+1 \end{eqnarray*}$$

• Por lo que al encontrar las raíces de esta ecuación cuadrática, se tiene que$$\begin{cases}
\lambda_{1}=\frac{39+\sqrt{1517}}{2} & =38.97434\\
\lambda_{2}=\frac{39-\sqrt{1517}}{2} & =0.02566
\end{cases}$$

$$\therefore\left\Vert A\right\Vert _{2}=\sqrt{38.97434}=6.24294338$$


In [ ]:
# Se define la matriz A
A = np.array([[2, 5],[1, 3]])
print (A)

# Calculamos la 2-norma de A
print (np.linalg.norm(A, 2))

[[2 5]
 [1 3]]
6.2429433838655335


## Norma de Frobenius

**Definición:** Sea $A\in M_{n\times n}$ sobre $\mathbb{R}^{n}$ y $\vec{x}\in\mathbb{R}^{n}$, la norma de Frobenius se define de la siguiente forma.

$$\left\Vert A\right\Vert _{F}=\left(\sum_{i=1}^{n}\sum_{j=1}^{n}\left|a_{ij}\right|^{2}\right)^{1/2}$$

Es una de las normas matriciales que más se emplea y ademas es compatible con la norma vectorial $\left\Vert \vec{x}\right\Vert _{2}$.

### Propiedades importantes

1.   Para la matriz $I$, $\left\Vert I\right\Vert _{F}=\sqrt{n}$, mientras que $\left\Vert I\right\Vert _{1}=\left\Vert I\right\Vert _{2}=\left\Vert I\right\Vert _{\infty}=1$.
2.   $\left\Vert A\right\Vert _{F}^{2}=traza\left(A^{T}A\right)$

### Ejemplo

Sea $A=\left(\begin{array}{cc}
1 & 2\\
3 & 4
\end{array}\right)$ calcular $\left\Vert A\right\Vert _{F}$

De acuerdo con la definición, se tiene que calcular:

| con $i=1$   | con $i=2$    | 
| :    -    :      | :       -        :          |
|$$j=1\,\Rightarrow\left|a_{11}\right|^{2}=\left|1\right|^{2}=1$$|$$j=1\,\Rightarrow\left|a_{21}\right|^{2}=\left|3\right|^{2}=9$$|
|$$j=2\,\Rightarrow\left|a_{12}\right|^{2}=\left|2\right|^{2}=4$$|$$j=2\,\Rightarrow\left|a_{22}\right|^{2}=\left|4\right|^{2}=16$$|

$$\therefore\left\Vert A\right\Vert _{F}=\sqrt{\left(1+4\right)+\left(9+16\right)}=\sqrt{30}=5.477225575$$

¿Existe otra forma de calcular la norma de Frobenius?.

¿Que puedes decir respecto a $\sqrt{traza\left(A^{T}A\right)}$?.

In [ ]:
# Definimos la matriz A
A = np.array([[1, 2],[3, 4]])
print (A)

# Calculamos la 2-norma de A
print (np.linalg.norm(A, "fro"))

[[1 2]
 [3 4]]
5.477225575051661


## Repaso normas Vectorial y Matricial

Por simplicidad, las normas matriciales y sus propiedades mostradas en esta presentación fueron definidas para el subespacio de las matrices $A\in M_{n\times n}$ sobre $\mathbb{R}^{n}$, sin embargo, las mismas definiciones y propiedades se pueden extender al subespacio de las matrices $A\in M_{m\times n}$ sobre $\mathbb{R}^{n}$ o incluso sobre $\mathbb{C}^{n}$.

Trata de realizar las siguientes demostraciones.

**Norma Vectorial**

1. $\left\Vert \vec{x}\right\Vert _{\infty}\leq\left\Vert \vec{x}\right\Vert _{2}$

2. $\left\Vert \vec{x}\right\Vert _{2}\leq\sqrt{n}\left\Vert \vec{x}\right\Vert _{\infty}$

**Norma Matricial**

3. $\left\Vert A\right\Vert _{\infty}\leq\sqrt{n}\left\Vert A\right\Vert _{2}$

4. $\left\Vert A\right\Vert _{2}\leq\sqrt{n}\left\Vert A\right\Vert _{\infty}$

### Demostración de 1

P.D. $\left\Vert \vec{x}\right\Vert _{\infty}\leq\left\Vert \vec{x}\right\Vert_{2}$

Sea $x\in\mathbb{R}^{n}$, por definición.

$$\left\Vert \vec{x}\right\Vert _{\infty}	=	\underset{1\leq i\leq n}{max}\left|x_{i}\right|
	=	\underset{1\leq i\leq n}{max}\left(\left|x_{i}\right|^{2}\right)^{1/2}
	\leq	\left(\sum_{i=1}^{n}\left|x_{i}\right|^{2}\right)^{1/2}=\left\Vert \vec{x}\right\Vert _{2}$$

$$\therefore	\left\Vert \vec{x}\right\Vert _{\infty}\leq\left\Vert \vec{x}\right\Vert _{2}	$$

### Demostración de 2

P.D. $\left\Vert \vec{x}\right\Vert _{2}\leq\sqrt{n}\left\Vert \vec{x}\right\Vert _{\infty}$ o $\left(1/\sqrt{n}\right)\left\Vert \vec{x}\right\Vert _{2}\leq\left\Vert \vec{x}\right\Vert _{\infty})$

Sea $x\in\mathbb{R}^{n}$, por definición.

$$\left\Vert \vec{x}\right\Vert _{2}	=	\left(\sum_{i=1}^{n}\left|x_{i}\right|^{2}\right)^{1/2}
	\leq	\left(\sum_{i=1}^{n}\underset{1\leq i\leq n}{max}\left|x_{i}\right|^{2}\right)^{1/2}
	=	\left(n\left\Vert \vec{x}\right\Vert _{\infty}^{2}\right)^{1/2}=\sqrt{n}\left\Vert \vec{x}\right\Vert _{\infty}
$$

$$\therefore	\left\Vert \vec{x}\right\Vert _{2}\leq	\sqrt{n}\left\Vert \vec{x}\right\Vert _{\infty}$$

### Demostración de 3

P.D. $\left\Vert A\right\Vert _{\infty}\leq\sqrt{n}\left\Vert A\right\Vert _{2}$

Sea $A\in M_{n\times n}$ sobre $\mathbb{R}^{n}$ y $x\in\mathbb{R}^{n}$, por definición.

$$\begin{eqnarray*}
\left\Vert A\right\Vert _{\infty}&=&\underset{\vec{x}\neq\vec{0}}{sup}\frac{\left\Vert A\vec{x}\right\Vert _{\infty}}{\left\Vert \vec{x}\right\Vert _{\infty}} \\
& \leq&\underset{\vec{x}\neq\vec{0}}{sup}\frac{\left\Vert A\vec{x}\right\Vert _{2}}{\left\Vert \vec{x}\right\Vert _{\infty}}\,\,\,\,\,\,(usando\,1\,en\,el\,numerador) \\
&\leq&\underset{\vec{x}\neq\vec{0}}{sup}\frac{\left\Vert A\vec{x}\right\Vert _{2}}{\left\Vert \vec{x}\right\Vert _{2}/\sqrt{n}}\,\,\,(usando\,2\,en\,el\,denominador) \\
&=&\sqrt{n}\left\Vert A\right\Vert _{2} \\
\therefore\left\Vert A\right\Vert _{\infty}&\leq&\sqrt{n}\left\Vert A\right\Vert _{2}
\end{eqnarray*}$$

### Demostración de 4

P.D. $\left\Vert A\right\Vert _{2}\leq\sqrt{n}\left\Vert A\right\Vert_{\infty}$

Sea $A\in M_{n\times n}$ sobre $\mathbb{R}^{n}$ y $x\in\mathbb{R}^{n}$, por definición...???.

## Referencias

*   Butt, R. (2009). Introduction to Numerical Analysis Using MATLAB®. Jones & Bartlett Learning.
* Cheney, W., & Kincaid, D. (2010). Métodos numéricos y computación (6a. Ed.). Cengage Learning Editores S.A. de C.V.
* Burden, R. L., Faires, J. D., & C, S. M. (1985). Análisis numérico. Grupo Editorial Iberoamérica.
* Skiba, Y. N. (2001). Introducción a los métodos numéricos. UNAM, Dirección General de Publicaciones y Fomento Editorial.
* http://www.ehu.eus/izaballa/Ana_Matr/Apuntes/lec2.pdf Accedido: 26 de noviembre de 2020.

#Evalúa tu conocimiento

Si deseas contestar un breve cuestionario en el que podras evaluar un poco del conocimiento aquirido en este notebook da clic en el siguiente enlace:


https://docs.google.com/forms/d/1hxSX7GSh_8JNo2DIwKJeaE-EIV8DYfp4up_PA5d9MmA/edit