<a href="https://colab.research.google.com/github/jugernaut/Prometeo/blob/master/02_AlgebraLineal/07_SistemasLineales/08_FactorizacionLU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Factorización A=LU
### Trabajo realizado con el apoyo del Programa UNAM-DGAPA-PAPIME PE101019
- Autor: Miguel Angel Pérez León
- Rev: dom nov 22 17:08:27 CDT 2020

Este sitio puede ser usado libremente, tanto por profesores como por estudiantes, que deseen complementar sus cursos y conocimientos en los temas antes mencionados. Los materiales están bajo una Licencia Creative Commons Atribución-NoComercial-CompartirIgual 4.0 Internacional

<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Licencia Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />Esta obra está bajo una <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Licencia Creative Commons Atribución-NoComercial-CompartirIgual 4.0 Internacional</a>.

## Introducción

A lo largo del curso se ha mostrado el por que es importante encontrar la forma de resolver un sistema del tipo $A\vec{x}=\vec{b}$.

Incluso se ha mencionado en diferentes ocasiones que el calculo de la matriz $A^{-1}$ es demasiado costoso.

Es por este motivo que para evadir el calculo de $A^{-1}$ se emplean alternativas como buscar la forma triangular superior de $A$ para después emplear substitución hacia atrás.

Sin embargo no siempre se puede garantizar que este algoritmo sea eficiente, por otro lado siempre podemos garantizar que la matriz $A$ puede ser descompuesta (factorizada) en el producto de dos matrices $LU$.

## Teorema

Sea $A\in M_{n\times n}$ una matriz **no singular también llamada regular**, (revisar <a href="../02_Matrices/02_Matrices.ipynb">Matrices</a>) se puede factorizar esta matriz en el producto de 2 matrices (únicas), una triangular inferior y otra triangular superior, es decir.

$$A=LU$$

En caso de que $A$ sea singular, **la unicidad de $L$ y $U$ no esta garantizada**.

Una vez que se tienen las matrices $L$ y $U$ resolver el sistema $A\vec{x}=\vec{b}$ se reduce a resolver dos sistemas, uno triangular inferior y posteriormente uno triangular superior.

Las letras $L$ y $U$ hacen referencia a que son matrices tinagulares, una inferior $L$ (es decir que todos los valores arriba de la diagonal principal son cero) y otra superior $U$ (es decir que todos los valores debajo de la diagonal principal son cero).

## $A\vec{x}=LU\vec{x}$

Ya que se tienen ambas matrices $\left(LU\right)$ podemos substituirlas en el sistema original, de tal manera que ahora el sistema luce así.

$$A\vec{x}=LU\vec{x}=\vec{b}$$

Posteriormente podemos replantear la solución del sistema de la siguiente forma.

$$LU\vec{x}=\vec{b}\Longrightarrow L^{-1}LU\vec{x}=L^{-1}\vec{b}\Longrightarrow U\vec{x}=L^{-1}\vec{b}\tag{1}$$

De manera tal que ahora nos interesa primero encontrar una solución al sistema $L^{-1}\vec{b}=\vec{y}$, mismo que podemos reescribir.

$$L^{-1}\vec{b}=\vec{y}\Longrightarrow LL^{-1}\vec{b}=L\vec{y}\Longrightarrow\vec{b}=L\vec{y}\Longrightarrow L\vec{y}=\vec{b}\tag{2}$$

La ecuación (2) tiene la ventaja de ser un sistema triangular inferior, es por eso que la solución $\vec{y}$ puede ser calculada fácilmente empleando **substitución hacia adelante**. Y una vez calculada, podemos proceder a resolver el segundo sistema empleando **substitución hacia atras**.

$$U\vec{x}=\vec{y}\tag{3}$$

## Algoritmo para la factorización $LU$

La idea detrás del algoritmo consiste en llevar a la matriz $A$ a su forma triangular superior $U$ mediante operaciones elementales y al mismo tiempo almacenar los factores multiplicativos que llevaron a la matriz $U$. Estos son multiplicados por -1 y almacenados en la matriz identidad que inicialmente es igual a $L$.

1.   Sean $A,U,L\in M_{n\times n}$, inicialmente las matrices $A$ y $U$ son iguales y $L$ es la identidad.
2.   Como se busca que $U$ sea una matriz triangular superior necesitamos generar ceros debajo de la diagonal.
3.   Supongamos que queremos generar un cero en la entrada $a_{\left(i,j\right)}$ $(j<i)$. Necesitamos multiplicar el renglón $r$ $(r<i)$ por un factor $f_{1}$ y sumarlo al renglón $i$.
4.   Al mismo tiempo es necesario substituir la entrada $l_{\left(i,j\right)}$ por $-f_{1}$. Es decir $l_{\left(i,j\right)}=-f_{1}$.
5.   Se repite, los pasos 3 y 4, hasta que la matriz $U$ alcanza su forma triangular superior.

### Ejemplo

Sean 

$$A=\left(\begin{array}{ccc}
-4 & -3 & 1\\
8 & 11 & -1\\
4 & 18 & 5
\end{array}\right)=U\;y\;L=\left(\begin{array}{ccc}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{array}\right)\Longrightarrow A=UL$$

Multipliquemos el renglón 1 de $A$ por **2** y lo sumamos al segundo renglón.

$$U=\left(\begin{array}{ccc}
-4 & -3 & 1\\
0 & 5 & 1\\
4 & 18 & 5
\end{array}\right)\quad L=\left(\begin{array}{ccc}
1 & 0 & 0\\
{\color{blue}{-2}} & 1 & 0\\
0 & 0 & 1
\end{array}\right)$$

Ahora multiplicamos el renglón 1 por **1** y se suma al tercer renglón.

$$U=\left(\begin{array}{ccc}
-4 & -3 & 1\\
0 & 5 & 1\\
0 & 15 & 6
\end{array}\right)\quad L=\left(\begin{array}{ccc}
1 & 0 & 0\\
-2 & 1 & 0\\
{\color{blue}{-1}} & 0 & 1
\end{array}\right)$$

Finalmente se multiplica por **-3** el segundo renglón y se suma al tercero.

$$U=\left(\begin{array}{ccc}
-4 & -3 & 1\\
0 & 5 & 1\\
0 & 0 & 3
\end{array}\right)\quad L=\left(\begin{array}{ccc}
1 & 0 & 0\\
-2 & 1 & 0\\
-1 & {\color{blue}3} & 1
\end{array}\right)$$

Comprobemos el resultado anterior en Python, es decir.

$$LU=A$$

In [1]:
# Se importan las bibliotecas necesarias
import numpy as np

# Generamos las matrices correspondientes
L = np.array([[1,0,0],[-2,1,0],[-1,3,1]])
U = np.array([[-4,-3,1],[0,5,1],[0,0,3]])

# Guardemos el resultado del producto de ambas matrices
A = np.matmul(L,U)

# Se comprueba el resultado
print(A)

[[-4 -3  1]
 [ 8 11 -1]
 [ 4 18  5]]


Ya que contamos con $LU$ y validamos que efectivamente $A=LU$, entonces se procede a resolver el sistema $L\vec{y}=\vec{b}$.

$$\left(\begin{array}{ccc}
1 & 0 & 0\\
-2 & 1 & 0\\
-1 & 3 & 1
\end{array}\right)\left(\begin{array}{c}
y_{0}\\
y_{1}\\
y_{2}
\end{array}\right)=\left(\begin{array}{c}
5\\
6\\
1
\end{array}\right)$$

Empleando **substitución hacia adelante** se tiene que. 

$$\vec{y}=\left(\begin{array}{c}
5\\
16\\
-42
\end{array}\right)$$

Ahora procedemos a resolver el sistema $U\vec{x}=\vec{y}$. 

$$
\left(\begin{array}{ccc}
-4 & -3 & 1\\
0 & 5 & 1\\
0 & 0 & 3
\end{array}\right)\left(\begin{array}{c}
x_{0}\\
x_{1}\\
x_{2}
\end{array}\right)=\left(\begin{array}{c}
5\\
16\\
-42
\end{array}\right)
$$

Finalmente, mediante **substitución hacia atras** se tiene que.

$$\vec{x}=\left(\begin{array}{c}
-9.25\\
6\\
-14
\end{array}\right)$$

De igual manera podemos comprobar el resultado mediante Python.

In [2]:
# Se define el vector b
b = np.array([5,6,1])

#Usamos numpy para validar la solucion
print(np.linalg.solve(A,b))

[ -9.25   6.   -14.  ]


## Método Doolittle o Crouti



Para la factorización de la matriz $A$, mediante el método de Doolittle, consistirá en igualar la matriz $A$ a dos matrices $L$ y $U$, una triangular inferior y la otra triangular superior respectivamente, pero la matriz $L$ presenta la particularidad de que los elementos ubicados en su diagonal, son iguales a 1, es decir, $l_{ii} = 1$. Es decir,

\begin{equation}
\begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{n1} & a_{n2} & \cdots & a_{nn}
\end{pmatrix}
=
\begin{pmatrix}
1 & 0 & \cdots & 0\\
l_{21} & 1 & \cdots & 0\\
\vdots & \vdots & \ddots & \vdots\\
l_{n1} & l_{n2} & \cdots & 1
\end{pmatrix}
\cdot
\begin{pmatrix}
u_{11} & u_{12} & \cdots & u_{1n}\\
0 & u_{22} & \cdots & u_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
0 & 0 & \cdots & u_{nn}
\end{pmatrix}
\end{equation} 

Obtener estas matrices con el método Doolittle se puede hacer uso del siguiente algoritmo para la obtención de cada entrada $u_{ij}$ y $l_{ij}$.

\begin{equation}
u_{ij}= \frac{a_{ij}- \sum_{k=1}^{j-1} l_{ik}u_{kj}}{l_{ii}}
\end{equation}

y para calcular los elementos de la matriz $L$

\begin{equation}
l_{ji}= \frac{a_{ji}- \sum_{k=1}^{i-1} l_{jk}u_{ki}}{u_{ii}}
\end{equation}


###Pseudocódigo
Utilizaremos la introducción anterior para construir el pseudocódigo del método Doolittle.


    funcion doolittle(recibe la matriz)
        L matriz diagonal
        U matriz de ceros
    #Primero llenaremos la primera columna de L y la primer fila de U
        for i en rango de la matriz:
        u[0,i]=a[0,i]
        l[i,0]=a[i,0]/u[0,0]

    #Llenamos los elementos restantes de U y de L respatando que son diagonales inferior y superior.
        for i en rango del segundo renglon/columna hasta la dimensión de la matriz
    #Para asegurarnos de no tocar los elementos inferiores/superiores de las diagonales
        for j en rango de i a la dimensión de la matriz
    #Creamos variables donde acumulemos las sumas
            suma de U 
            suma de L
    #Vamos a acumular las sumas
            for k en rango a i
                suma de U =+ l[i,k]*u[k,j]
                suma de L =+ l[j,k]*u[k,i]
    #Los valores de uij y lij seran segun definicion
            Uij=aij-suma de U
            Lji=aji-suma de L / uii
    #Solo resta que nos regrese U y L
        return U,L










###Código

Una condición a verificar es que la matriz es invertible

In [7]:
#Importamos librerias
import numpy as np

In [8]:
#Verificamos condición
def invertible(A):
    if np.linalg.det(A) !=0 : 
        print("La matriz es invertible")
    else: 
        print("La matriz NO es invertible")

# Pueba 
A = np.array([[6.0, 2.0, 1.0, -1.0],[2.0, 4.0, 1.0, 0.0],[1.0, 1.0, 4.0, -1.0],[-1.0, 0.0, -1.0, 3.0]])
invertible(A)

La matriz es invertible


Código de método Doolittle

In [12]:
# Ejecutamos el método
def doolittle(matriz):
    A=np.transpose(matriz)
    L=np.identity(A.shape [1])
    U= np.zeros([A.shape[0], A.shape[1]])
    # validar matriz definida y positiva
    for d in range(A.shape[0]):
        U[0,d]=A[0,d]
        L[d,0]=A[d,0]/U[0,0]

    for i in range(1,A.shape[0]):
        for j in range(i,A.shape[0]):
            sumU=0.0
            sumL=0.0
            for k in range(i):
                sumU= sumU+(L[i,k]*U[k,j])
                sumL= sumL+(L[j,k]*U[k,i])
            U[i,j]=(A[i,j]-sumU)
            L[j,i]=(A[j,i]-sumL)/U[i,i]
    
    return U, L


### Ejemplo
Aplicaremos el método para la aiguiente matriz

$$A = \left(\begin{array}{ccc}
6 & 2 & 1 & -1\\
2 & 4 & 1 & 0\\
1 & 1 & 4 & -1 \\
-1 & 0 & -1 & 3
\end{array}\right)$$

Observando que el método nos regresa La matríz U y la matriz L.

In [16]:
# Pueba 
A = np.array([[6.0, 2.0, 1.0, -1.0],[2.0, 4.0, 1.0, 0.0],[1.0, 1.0, 4.0, -1.0],[-1.0, 0.0, -1.0, 3.0]])
#Usando el método nos regresara U y L (en ese orden)
U, L = doolittle(A)   

np.matmul(L, U)

array([[ 6.00000000e+00,  2.00000000e+00,  1.00000000e+00,
        -1.00000000e+00],
       [ 2.00000000e+00,  4.00000000e+00,  1.00000000e+00,
         0.00000000e+00],
       [ 1.00000000e+00,  1.00000000e+00,  4.00000000e+00,
        -1.00000000e+00],
       [-1.00000000e+00,  5.55111512e-18, -1.00000000e+00,
         3.00000000e+00]])

## Análisis de la complejidad

*   ¿Cuantos flop's (en términos de n) requiere unicamente el algoritmo de la substitución hacia adelante?.
*   ¿La factorización $A=LU$ funciona para cualquier sistema de ecuaciones?.
*   ¿Que sucede si en el sistema original $A\vec{x}=\vec{b}$ se tiene un cero en alguna entrada que impida realizar la factorización $A=LU$?.

## Ejemplo de sistema lineal

A continuación se muestra el codigo en python de la factorización $A=LU$ y como emplearlo para resolver un sistema de ecuaciones lineales del tipo $A\vec{x}=\vec{b}$.

In [ ]:
# algoritmo para descomposicion A=LU
# la matriz A ya esta dada
def factorizacionLU(A):
    # dimension de la matriz
    n = len(A)
    # matriz L inicialmente es la identidad
    L = np.identity(n)
    # inicialmente la matriz A y la matriz U son iguales
    U = np.zeros((n,n))
    for i in range(0,n):
        for j in range(0,n):
            U[i][j] = A[i][j]
    # eliminacion gaussiana
    for i in range(0,n):
        for j in range(i+1,n):
            # guardar los factores de eliminacion gaussiana 
            # en la matriz L
            factor = U[j][i]/U[i][i]
            L[j][i] = factor
            # realizar eliminacion gaussiana en la matriz U
            # para quedar de forma triangular superior
            for k in range(i,n):
                U[j][k] = U[j][k] - factor*U[i][k]
    return L,U

# algoritmo para sustitucion hacia delante
# n es el tamano de la dimension del problema
# matriz L, vector b ya estan dados como parametros
# guardar los resultados en el vector y
# Ly=b
def sustDelante(L, b):
    n=len(L)
    y=np.empty_like(b)
    y[0] = b[0]
    for i in range(1,n):
        y[i] = b[i]
        for j in range(0,i):
            y[i] -= L[i][j]*y[j]
    return y

# algoritmo para sustitucion hacia atras
# n es el tamano de la dimension del problema
# matriz U, vector y ya estan dados como parametros
# guardar los resultados en el vector x
# Ux=y
def sustAtras(U, y):
    n=len(U)
    x=np.empty_like(y)
    x[n-1] = y[n-1]/U[n-1][n-1]
    for i in range(n-2,-1,-1):
        x[i] = y[i]
        for j in range(i+1,n):
            x[i] -= U[i][j]*x[j]
        x[i] /= U[i][i]
    return x

def main():
    # matriz del sistema Ax=b
    A = np.array([[-4.0,-3.0,1.0],[8.0,11.0,-1.0],[4.0,18.0,5.0]])
    # vector b = A*xTeor, producto matriz A con vector xTeor 
    b = np.array([5.0,6.0,1.0])
    # llamar funcion de descomposicion LU para obtener/llenar matrices L,U
    L,U=factorizacionLU(A)
    #se imprimen las matrices y el vector b
    print(A)
    print(L)
    print(U)
    print(b)
    # llamar funcion sustDelante para obtener/llenar vector y
    y = sustDelante(L,b)    
    # llamar funcion sustAtras para obtener/llenar vector x 
    # solucion aproximada/calculada
    x = sustAtras(U,y)
    # imprimir solucion aproximada/calculada
    print(x)
    
main()

[[-4. -3.  1.]
 [ 8. 11. -1.]
 [ 4. 18.  5.]]
[[ 1.  0.  0.]
 [-2.  1.  0.]
 [-1.  3.  1.]]
[[-4. -3.  1.]
 [ 0.  5.  1.]
 [ 0.  0.  3.]]
[5. 6. 1.]
[ -9.25   6.   -14.  ]


# Referencias

*   Butt, R. (2009). Introduction to Numerical Analysis Using MATLAB®. Jones & Bartlett Learning.
*   Cheney, W., & Kincaid, D. (2010). Métodos numéricos y computación (6a. Ed.). Cengage Learning Editores S.A. de C.V.
*   Burden, R. L., Faires, J. D., & C, S. M. (1985). Análisis numérico. Grupo Editorial Iberoamérica.
*   Skiba, Y. N. (2001). Introducción a los métodos numéricos. UNAM, Dirección General de Publicaciones y Fomento Editorial.

#Evalúa tu conocimiento 

Si deseas contestar un breve cuestionario en el que podras evaluar un poco del conocimiento aquirido en este notebook da clic en el siguiente enlace:


https://docs.google.com/forms/d/e/1FAIpQLScEtLeKQZnGpdISgAnV_HIf2F-j7bhPPcnsYnxoNLWazEC9uA/viewform?usp=sf_link