<a href="https://colab.research.google.com/github/jugernaut/Prometeo/blob/desarrollo/02_AlgebraLineal/07_SistemasLineales/11_Substituciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Substituciones (hacia adelante, hacia atras)
### Proyecto PAPIME PE101019
- Autor: Miguel Angel Pérez León
- Rev: mar jun  24 17:08:27 CDT 2020

Una vez que ya se tiene una matriz triangular (superior o inferior) es muy sencillo resolver un sistema de ecuaciones empleando alguna de estas substituciones.

La idea general es que dado un sistema del tipo $A\vec{x}=\vec{b}$, la matriz $A\in M_{n\times n}$ puede ser factorizada empleando alguno de los metodos previamente mencionados (LU, QR, Cholesky) y una vez que se tenga alguna de estas factorizaciones es posible emplear algun tipo de subtitución para resolver el sistema original.

## Substitución hacia adelante

Supongamos que se tiene una matríz triangular inferior y los correspondientes vectores, $L\in\mathbb{R}_{n\times n}\,\vec{y},\vec{b}\in\mathbb{R}^{n}$ podemos pensar en resolver el sistema. 

$$L\vec{y}=\vec{b}$$

Para resolver dicho sistema empleamos el siguiente algoritmo de substitución.

$$y_{i}=\frac{b_{i}-\displaystyle\sum_{j=0}^{i-1}l_{ij}y_{j}}{l_{ii}}\quad i=0,\ldots,(n-1)$$

## Ejemplo

$$\left(\begin{array}{ccc}
1 & 0 & 0\\
-2 & 1 & 0\\
-1 & 3 & 1
\end{array}\right)\left(\begin{array}{c}
y_{0}\\
y_{1}\\
y_{2}
\end{array}\right)=\left(\begin{array}{c}
5\\
6\\
1
\end{array}\right)$$

Encontrar la primera entada del vector $\vec{y}$ es trivial

$$y_{0}=5$$

La siguiente entrada involucra a $y_{0}$ es decir.

$$y_{1}=\frac{6-\left(\left(-2\right)\left(y_{0}\right)\right)}{l_{11}}=\frac{6-\left(\left(-2\right)\left(5\right)\right)}{1}=16$$

Finalmente la ultima entrada de $y$ se se calcula emplenado $y_{1}$ y $y_{0}$.

$$y_{2}=\frac{1-\left(\left(-1\right)\left(y_{0}\right)+\left(3\right)\left(y_{1}\right)\right)}{l_{22}}=\frac{1-\left(\left(-1\right)\left(5\right)+\left(3\right)\left(16\right)\right)}{1}=-42$$

Empleando **substitución hacia adelante** se tiene que. 

$$\vec{y}=\left(\begin{array}{c}
5\\
16\\
-42
\end{array}\right)$$

## Substitución hacia atras

Supongamos que se tiene una matríz triangular superior y los correspondientes vectores, $U\in\mathbb{R}_{n\times n}\,\vec{x},\vec{y}\in\mathbb{R}^{n}$ podemos pensar en resolver el sistema. 

$$U\vec{x}=\vec{y}$$

Para resolver dicho sistema empleamos el siguiente algoritmo de substitución.

$$x_{i}=\frac{y_{i}-\displaystyle\sum_{j=i+1}^{n-1}u_{ij}x_{j}}{u_{ii}}\quad i=(n-1),\ldots,0$$

## Ejemplo

$$
\left(\begin{array}{ccc}
-4 & -3 & 1\\
0 & 5 & 1\\
0 & 0 & 3
\end{array}\right)\left(\begin{array}{c}
x_{0}\\
x_{1}\\
x_{2}
\end{array}\right)=\left(\begin{array}{c}
5\\
16\\
-42
\end{array}\right)
$$

Encontrar la última entada del vector $\vec{x}$ es trivial

$$x_{2}=\frac{-42}{u_{22}}=\frac{-42}{3}=-14$$

La siguiente entrada involucra a $x_{2}$ es decir.

$$x_{1}=\frac{16-\left(\left(1\right)\left(x_{2}\right)\right)}{u_{11}}=\frac{16-\left(\left(1\right)\left(-14\right)\right)}{5}=6$$

Finalmente la primer entrada de $x$ se se calcula emplenado $x_{2}$ y $x_{1}$.

$$x_{0}=\frac{5-\left(\left(1\right)\left(x_{2}\right)+\left(-3\right)\left(x_{1}\right)\right)}{u_{00}}=\frac{5-\left(\left(1\right)\left(-14\right)+\left(-3\right)\left(6\right)\right)}{-4}=-9.25$$

Finalmente, mediante **substitución hacia atras** se tiene que.

$$\vec{x}=\left(\begin{array}{c}
-9.25\\
6\\
-14
\end{array}\right)$$

## En python ambos algoritmos lucen asi

In [4]:
import numpy as np

# algoritmo para sustitucion hacia delante
# n es el tamano de la dimension del problema
# matriz L, vector b ya estan dados como parametros
# guardar los resultados en el vector y
# Ly=b
def sustDelante(n, L, b, y):
  y[0] = b[0]
  for i in range(1,n):
    y[i] = b[i]
    for j in range(0,i):
      y[i] -= L[i][j]*y[j]
  return

# algoritmo para sustitucion hacia atras
# n es el tamano de la dimension del problema
# matriz U, vector y ya estan dados como parametros
# guardar los resultados en el vector x
# Ux=y
def sustAtras(n, U, y, x):
    x[n-1] = y[n-1]/U[n-1][n-1]
    for i in range(n-2,-1,-1):
      x[i] = y[i]
      for j in range(i+1,n):
        x[i] -= U[i][j]*x[j]
      x[i] /= U[i][i]
    return

#Ejemplo con un sistema de ecuaciones

Supongamos que tenemos el sistema $A\vec{x}=\vec{b}$.

$$\left(\begin{array}{ccc}
-4 & -3 & 1\\
8 & 11 & -1\\
4 & 18 & 5
\end{array}\right)\left(\begin{array}{c}
x_{0}\\
x_{1}\\
x_{2}
\end{array}\right)=\left(\begin{array}{c}
5\\
6\\
1
\end{array}\right)$$

Y su respectiva factorización $A=LU$.

$$U=\left(\begin{array}{ccc}
-4 & -3 & 1\\
0 & 5 & 1\\
0 & 0 & 3
\end{array}\right)\quad L=\left(\begin{array}{ccc}
1 & 0 & 0\\
-2 & 1 & 0\\
-1 &{3} & 1
\end{array}\right)$$

In [7]:
U = np.array([[-4,-3,1],[0,5,1],[0,0,3]])
L = np.array([[1,0,0],[-2,1,0],[-1,3,1]])

print(np.matmul(L,U))

[[-4 -3  1]
 [ 8 11 -1]
 [ 4 18  5]]


Primero encontramos la solución del sistema $L\vec{y}=\vec{b}$ empleando sistitución hacia atras.

In [8]:
b = np.array([5,6,1])
y = np.zeros(3)
sustDelante(y.size, L, b, y)

print(y)

[  5.  16. -42.]


Ya que se conoce el valor del vector $\vec{y}$ ahora podemos resolver el sistema $U\vec{x}=\vec{y}$

In [ ]:
x = np.zeros(3)
sustAtras(x.size, U, y, x)

print(x)

[ -9.25   6.   -14.  ]


Por lo tanto la solución al sistema original $A\vec{x}=\vec{b}$, es.

$$\vec{x}=\left(\begin{array}{c}
-9.25\\
6\\
-14
\end{array}\right)$$

#Resúmen

Los algoritmos de substitución hacia atras y hacia adelante son de los algoritmos mas elementales para resolver un sistema de ecuaciones, sin embargo vale la pena notar algunas cosas.

*   ¿Por que es buena idea emplear estos algoritmos en lugar de buscar la inversa de la matriz $A$?.
*   En terminos de elementales (+, -, *, /), ¿cuantas operaciones se realizan al emplear el algoritmo de sustitución hacia adelante?.
*   En terminos de operaciones (+, -, *, /), ¿cuantas operaciones se realizan al emplear el algoritmo de sustitución hacia atras?.
*   En total, ¿cuantas operaciones se realizan cuando se resuelve un sistema $LU\vec{x}=\vec{b}$ empleando sustitución hacia adelante y despues hacia atras?.





##Referencias

Justin Solomon: Numerical Algorithms.

Jaan Kiusalaas: Numerical Methods in Engineering with Python.

Richard L. Burden, J. Douglas Faires: Análisis Numérico, Math Learning.

Riswan Butt: Numerical Analysys Using Matlab, Jones and Bartlett.

Ward Cheney, David Kincaid: Métodos Numéricos y Computación, Cenage Learning.