<a href="https://colab.research.google.com/github/jugernaut/Prometeo/blob/desarrollo/02_AlgebraLineal/03_Determinantes/03_Determinantes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Determinantes 
### **Trabajo realizado con el apoyo del Programa UNAM-DGAPA-PAPIME PE101019**
*   Autor: 
    - Ocampo Nava Maria Fernanda
*   Rev: Mier Dic 02 17:15:32 CDT 2020


### Problema inicial

Calcular el área de un triángulo cuyos vértices son: $A(2, 0), B(3,4)$ y $C(-2,5)$



##**Introducción**


La función determinante de una matriz es una herramienta que nos permite clasificar los sistemas de ecuaciones lineales según sus soluciones.
La definición de determinante no es sencilla, sin embargo existen reglas que ayudan a obtenerlo dependeiendo la dimensión de la matriz, es importante saber que esto solo funciona con matrices cuadradas.




##**Definición de determinante**

Sea $A \in M_{n\times n}$ sobre $\mathbb{R}$ el determinante de $A$ se define como sigue.

$$det(A)=\begin{cases}
a_{0,0}*a_{1,1}-a_{0,1}*a_{1,0} & n=2\\
\sum_{i=0}^{n-1}\left(-1\right)^{i}*a_{0,i}*det\left(subMatriz_{0,i}\left(A\right)\right) & n\geq2
\end{cases}$$

Donde la función $subMatriz_{0,i}\left(A\right)$ elimina el renglón cero y la columna $i$ de la matriz $A$.

Algo que tambien es importante mencionar es que los determinantes son de gran utilidad por ejemplo para:

#### Ejemplo de 3x3

$$A=\left(\begin{array}{ccc}
4 & 3 & 1\\
7 & 5 & -1\\
4 & 9 & 5
\end{array}\right)$$

$det(A)=\left(-1\right)^{0}\left(4\right)\left(det\left(\left(\begin{array}{cc}
5 & -1\\
9 & 5
\end{array}\right)\right)\right)\left(-1\right)^{1}\left(3\right)\left(det\left(\left(\begin{array}{cc}
7 & -1\\
4 & 5
\end{array}\right)\right)\right)\left(-1\right)^{2}\left(1\right)\left(det\left(\left(\begin{array}{cc}
7 & 5\\
4 & 9
\end{array}\right)\right)\right)=62$

In [1]:
# se importan las paqueterias necesarias
import numpy as np

#Funcion auxiliar para eliminar un renglon y una columna
def subMatriz(mat, ren, col):
    copia = np.copy(mat)
    copia = np.delete(copia, (ren), axis=0)
    copia = np.delete(copia, (col), axis=1)
    return copia

# Determinante
# devuelve el determinante de la matriz m1
# se asume que m1 es cuadrada
def det(m1):
    if len(m1) == 2:
      return m1[0][0]*m1[1][1]-(m1[0][1]*m1[1][0])
    else:
      determinante = 0.0
      for i in range(len(m1[0])):
        determinante += ((-1)**i)*(m1[0][i])*det(subMatriz(m1,0,i))
    return determinante

a = np.array([[4,3,1],[7,5,-1],[4,9,5]])
#se muestran ambas matrices
print(a)
#se imprime la multiplicacion
print(det(a))

print(np.linalg.det(a))

[[ 4  3  1]
 [ 7  5 -1]
 [ 4  9  5]]
62.0
62.00000000000001



## **Cálculo de áreas de figuras en el plano**

El cálculo de áreas de polígonos en el plano, de los que se conocen o bien las coordenadas de los vértices o bien las de ciertos vectores, puede efectuarse mediante el cálculo de determinantes. 



### **Obtención de la ecuación implícita de un plano**

La obtención de la ecuación implícita de un plano, puede efectuarse mediante el desarrollo de un determinante nulo, cuyas entradas están en función de las coordenadas de tres puntos no alineados de dicho plano.


Si tenemos una matriz de la siguiente forma:


$$\begin{equation} A_{1\times 1} =
\begin{pmatrix}
 a_{11} 
\end{pmatrix}
\end{equation}$$

entonces $det(A)$= $ a_{11} $

para una matriz de ${2 \times 2}$, es decir:

$$\begin{equation} A_{2\times 2} =
\begin{pmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22} 
\end{pmatrix}
\end{equation}$$

entonces $det(A)$= $ a_{11} $ x $ a_{22} $ - $ a_{12} $ x $ a_{21} $

El cálculo de los determinantes se vuelve mas complejo conforme la dimensión de la matriz aumenta.
A continuación se muestra como obtener el determinante con numpy.

In [ ]:
# Iportamos la libreria que  da soporte para crear vectores y matrices grandes multidimensionales, 
#Junto con una gran colección de funciones matemáticas de alto nivel para operar con ellas
import numpy as np

#Pedimos que nos de la leyenda que nos pida ingresar la matriz
print("Ingrese la matriz a la que se le sacará el determinante")

#Pedimos que ingrese el número de filas y columnas que tiene la matriz
print("Recuerde que debe ingresar una matriz cuadrada")

filas = int(input ("Indique el número de filas: "))

#Creamos la matriz en las que se guardarán los valores que el usuario proporcione 
matriz1 = np.zeros((filas,filas))
#Le pedimos que ingrese la matriz elemento por elemento y vamos llenando
print ('Ingrese la matriz')
for i in range(filas):
		for j in range(filas):
			matriz1[i][j] = np.array( float(input('Elemento (%d,%d): ' % (i, j))))
	 
print("su matriz es:" )
print(matriz1)

#sacamos el determinante
#Mediante la función linealg.det() de Numpy obtenemos el determinante
print("El determinante de su matriz es:",np.linalg.det(matriz1))

Ingrese la matriz a la que se le sacará el determinante
Recuerde que debe ingresar una matriz cuadrada
Indique el número de filas: 2
Ingrese la matriz
Elemento (0,0): 2
Elemento (0,1): 2
Elemento (1,0): 2
Elemento (1,1): 2
su matriz es:
[[2. 2.]
 [2. 2.]]
El determinante de su matriz es: 0.0


## **Propiedades de los determinantes**

* El determinante de una matriz triangular es igual al producto de sus componentes en la diagonal.
Es decir que sea $A$ una matriz como la que se muestra a continuacion:

$$\begin{equation} A_{n\times n} =
\begin{pmatrix}
a_{11} & 0 & \cdots & 0\\
a_{21} & a_{22} & \cdots & 0\\
\vdots & \vdots & \ddots & \vdots\\
a_{n1} & a_{n2} & \cdots & a_{nn}
\end{pmatrix}
\end{equation}$$

Entonces $det(A)$= $a_{11}$*$a_{22}$*$a_{33}$*....*$a_{nn}$



In [ ]:
#Matriz diagonal 
print("Matriz diagonal A de dimensión 3x3, :")

#Creamos la matriz mediante un arreglo 
A= np.array([[11,2,3],[0,1,4],[0,0,2]])
#Imprimimos la matriz creada
print(A)

#sacamos el determinante mediante linalg de la paqueteria numpy
print("El determinante de su matriz es:", np.linalg.det(A))




Matriz diagonal A de dimensión 3x3, :
[[11  2  3]
 [ 0  1  4]
 [ 0  0  2]]
El determinante de su matriz es: 22.000000000000004


Si una matriz $B$ se obtiene intercambiando dos filas o intercambiando dos columnas de una matriz $A$ entonces:

 $det(B)$ = $−det(A)$

In [ ]:
print("Matriz A de dimensión 2x2, :")

A= np.array([[11,2,3],[0,1,4],[6,4,2]])
print(A)

#Sacamos el determinante de A
print("El determinante de su matriz A es:", np.linalg.det(A))

print("Matriz B de dimensión 2x2, :")
B= np.array([[2,11,3],[1,0,4],[4,6,2]])
print(B)

#sacamos el determinante de B
print("El determinante de su matriz B es:", np.linalg.det(B))



Matriz A de dimensión 2x2, :
[[11  2  3]
 [ 0  1  4]
 [ 6  4  2]]
El determinante de su matriz A es: -124.00000000000003
Matriz B de dimensión 2x2, :
[[ 2 11  3]
 [ 1  0  4]
 [ 4  6  2]]
El determinante de su matriz B es: 123.99999999999991


Si $A$ y $B$ son matrices diagonales de ${n \times n}$, entonces $det AB$=$det A$ $det B$. 

Si $A$ y $B$ son matrices triangulares inferiores, entonces $AB$=$det A$ $det B$. 

In [ ]:
#Solicitamos al usuario las matrices 
print("recuerde que deben ser matrices cuadradas y diagonales")
filas1 = int(input ("Indique el número de filas y columnas de la matriz: "))


#creamos las matrices en las que se guardarán los valores que el usuario proporcione y los de la suma
A = np.zeros((filas1,filas1))    
B = np.zeros((filas1,filas1))   
 #llenamos la matriz 1 con los datos del usuario
print ("Ingrese la primer matriz")

for i in range(filas1):
        for j in range(filas1):
            A[i][j] = float(input('Elemento (%d,%d): ' % (i, j)))
print( "su matriz 1 es:")
print(A)
#llenamos la matriz 2
print ("Ingrese la segunda matriz")
for i in range(filas1):
        for j in range(filas1):
            B[i][j] = float(input('Elemento (%d,%d): ' % (i, j)))
print( "su matriz 2 es:")
print(B)

#Recordamos que la función dot() nos devuelve un producto matricial
C = A.dot(B)
print("El producto de las matrices es:",C)

print("El determinante de su matriz A es:", np.linalg.det(A))

print("El determinante de su matriz B es:", np.linalg.det(B))

print("El determinante de su matriz A*B es:", np.linalg.det(C))


recuerde que deben ser matrices cuadradas y diagonales
Indique el número de filas y columnas de la matriz: 2
Ingrese la primer matriz
Elemento (0,0): 2
Elemento (0,1): 3
Elemento (1,0): 0
Elemento (1,1): 3
su matriz 1 es:
[[2. 3.]
 [0. 3.]]
Ingrese la segunda matriz
Elemento (0,0): 3
Elemento (0,1): 4
Elemento (1,0): 0
Elemento (1,1): 3
su matriz 2 es:
[[3. 4.]
 [0. 3.]]
El producto de las matrices es:
[[ 6. 17.]
 [ 0.  9.]]
El determinante de su matriz A es:
6.0
El determinante de su matriz B es:
9.000000000000002
El determinante de su matriz A*B es:
54.00000000000001


No se cumple en general que el $det (A + B)$=$det A + det B$

In [ ]:
A= np.array([[11,2],[0,1]])
print(A)

#sacamos el determinante
print("El determinante de su matriz es:", np.linalg.det(A))

S= np.array([[23,12],[11,3]])
print(S)

#sacamos el determinante
print("El determinante de su matriz es:", np.linalg.det(S))


print("La suma de las matrices es:")
T=A+S

print("El determinante de su matriz suma es:", np.linalg.det(T))


[[11  2]
 [ 0  1]]
El determinante de su matriz es: 11.000000000000002
[[23 12]
 [11  3]]
El determinante de su matriz es: -62.99999999999999
La suma de las matrices es:
El determinante de su matriz suma es: -17.999999999999996


Si dos filas (columnas) de $A$ son iguales, entonces $det(A) = 0$

In [ ]:
S= np.array([[23,12],[23,12]])
print(S)

#Sacamos el determinante
print("El determinante de su matriz es:", np.linalg.det(S))


[[23 12]
 [23 12]]
El determinante de su matriz es: 0.0


El determinante de una matriz con un escalar es el escalar por el determinante de la matriz, es decir:

Si $C$= $\tau$*$A_{n\times n}$ ,  
entonces $det(C)$= $\tau$ * det($A_{n\times n}$)

Estas son solo algunas de las propiedades que los determinantes poseen.



## **Cálculo de determinantes por el método de desarrollo por menores**

Para el cálculo de determinantes por este método se toma como referencia una fila o una columna y se va eliminando sus elementos (de acuerdo a su posición) y formando los determinantes de un orden inferior a la matriz original; el cual queda multiplicado por este elemento y su signo de posición. Es decir cada elemento de la fila o la columna seleccionada se multiplica por su determinante menor y el signo de posición. 

Los signos de posición se obtienen siempre comenzando con positivo y alternando luego. 

Por ejemplo para una matriz ${3 \times 3}$ los signos serían :


$$\begin{equation} A_{3\times 3} = 
\begin{pmatrix}
+ & - & +  \\
- & + & - \\
+ & - & +
\end{pmatrix}
\end{equation}$$

Para una matriz de ${4\times 4}$ se tiene:

$$\begin{equation} A_{4\times 4} = 
\begin{pmatrix}
+ & - & + & - \\
- & + & - & + \\
+ & - & + & - \\
- & + & - & + 
\end{pmatrix}
\end{equation}$$

Para una matriz de ${5\times 5}$ se tiene:

$$\begin{equation} A_{5\times 5} = 
\begin{pmatrix}
+ & - & + & - & +\\
- & + & - & + & - \\
+ & - & + & - & + \\
- & + & - & + & - \\
+ & - & + & - & +
\end{pmatrix}
\end{equation}$$

y asi sucesivamente se lleva a cabo el procedimiento antes descrito, por ejemplo calcularemos el determinante de una matriz de ${3\times 3}$.

$$\begin{equation} A_{3\times 3} = 
\begin{pmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21}& a_{22} & a_{23}\\
a_{31}& a_{32}& a_{33}
\end{pmatrix}
\end{equation}$$

Entonces como primer paso tomamos el primer elemento y lo multiplicamos por el determinante de la matriz que se obtiene al eliminar la primera fila y la primer columna, es decir:

- primer elemento del determinante :

$$\begin{equation}
a_{11}*\begin{vmatrix}
a_{22} & a_{23}\\
a_{32} & a_{33}
\end{vmatrix}= + a_{11}*[(a_{22}*a_{33})-(a_{23}*a_{32})]=a
\end{equation}$$

- segundo elemento del determinante :
para este se toma el segundo elemento de la matriz y se multiplica por el determinante de la matriz que resta al quitar el primer renglón y la segunda columna.


$$\begin{equation}
-a_{12}*\begin{vmatrix}
a_{21} & a_{23}\\
a_{31} & a_{33}
\end{vmatrix}= - a_{12}*[(a_{21}*a_{33})-(a_{23}*a_{31})]=b
\end{equation}$$

- tercer elemento del determinante :
para este se toma el tercer elemento de la matriz y se multiplica por el determinante de la matriz que resta al quitar el primer renglón y la tercer columna.

$$\begin{equation}
+a_{13}*\begin{vmatrix}
a_{21} & a_{22}\\
a_{31} & a_{32}
\end{vmatrix}= a_{13}*[(a_{21}*a_{32})-(a_{22}*a_{31})]=c
\end{equation}$$


Todo lo anterior tomando en cuenta los signos de los elemntos según la posición del elemnto y el signo qe le corresponde por lo que se explico al inicio del método. 
Por último se obtiene que:


$$\begin{equation} det(A) = 
\begin{pmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21}& a_{22} & a_{23}\\
a_{31}& a_{32}& a_{33}
\end{pmatrix} = \pm a \pm b \pm c
\end{equation}$$

De manera similar se hace lo anterior con matrices de orden mayor hasta que se logre disminuir a un orden en el que sea mas fácil calcular el determinante.


## **Referencias**

•	Kolman, B., & Hill, D. R. (2006). Algebra lineal. Pearson Educación.

•	Grossman, S., & Flores Godoy, J. J. (2012). Álgebra Lineal (Séptima edición). McGraw Hill.

