# Determinantes
# Papime pe101019
### Última modificación: 9-Septiembre-2020 12:59
### Autor: Maria Fernanda Ocampo 


### Problema inicial

Calcular el área de un triángulo cuyos vértices son: A(2, 0), B(3,4) y C(-2,5)

### Introducción

La función determinante de una matriz es una herramienta que nos permite clasificar los sistemas de ecuaciones lineales según sus soluciones.
La definicón de determinante no es sencilla, sin embargo existen reglas que ayudan a obtenerlo dependeiendo la dimensión de la matriz, es importante saber que esto solo funciona con matrices cuadradas.

Algo que tambien es importante mencionar es que los determinantes son de gran utilidad por ejemplo para:

- CÁLCULO DE ÁREAS DE FIGURAS EN EL PLANO
El cálculo de áreas de polígonos en el plano, de los que se conocen o bien las coordenadas de los vértices o bien las de ciertos vectores, puede efectuarse mediante el cálculo de determinantes. 

-OBTENCIÓN DE LA ECUACIÓN IMPLÍCITA DE UN PLANO
La obtención de la ecuación implícita de un plano, puede efectuarse mediante el desarrollo de un determinante nulo, cuyas entradas están en función de las coordenadas de tres puntos no alineados de dicho plano.


Si tenemos una matriz de la siguiente forma:


\begin{equation} A_{1x1}=
\begin{pmatrix}
 a_{11} 
\end{pmatrix}
\end{equation}

entonces det(A)= $ a_{11} $

para una matriz de 2x2, es decir:

\begin{equation} A_{2x2} =
\begin{pmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22} 
\end{pmatrix}
\end{equation}

entonces det(A)= $ a_{11} $ x $ a_{22} $ - $ a_{12} $ x $ a_{21} $

El cálculo de los determinantes se vuelve mas complejo conforme la dimensión de la matriz aumenta.
A continuación se muestra como otener el determinante con numpy.

In [ ]:
import numpy as np
print("Ingrese la matriz a la que se le sacará el determinante")
#pedimos que nos de el número de filas y columnas que tiene la matriz
print("Recuerde que debe ingresar una matriz cuadrada")
filas = int(input ("Indique el número de filas: "))

#creamos la matriz en las que se guardarán los valores que el usuario proporcione 
matriz1 = np.zeros((filas,filas))
#le pedimos que ingrese la matriz elemento por elemento y vamos llenando
print ('Ingrese la matriz')
for i in range(filas):
		for j in range(filas):
			matriz1[i][j] = np.array( float(input('Elemento (%d,%d): ' % (i, j))))
print("su matriz es:")
print(matriz1)
#sacamos el determinante
print("El determinante de su matriz es:")
z= np.linalg.det(matriz1)
print(z)

Ingrese la matriz a la que se le sacará el determinante
Recuerde que debe ingresar una matriz cuadrada
Indique el número de filas: 2
Ingrese la matriz
Elemento (0,0): 11
Elemento (0,1): 21
Elemento (1,0): 34
Elemento (1,1): 2
su matriz es:
[[11. 21.]
 [34.  2.]]
El determinante de su matriz es:
-691.9999999999998


## Propiedades de los determinantes

* El determinante de una matriz triangular es igual al producto de sus componentes en la diagonal.
Es decir que sea A una matriz como la que se muestra a continuacion:

\begin{equation} A_{nxn} =
\begin{pmatrix}
a_{11} & 0 & \cdots & 0\\
a_{21} & a_{22} & \cdots & 0\\
\vdots & \vdots & \ddots & \vdots\\
a_{n1} & a_{n2} & \cdots & a_{nn}
\end{pmatrix}
\end{equation}

Entonces det(A)= $a_{11}$*$a_{22}$*$a_{33}$*....*$a_{nn}$



In [ ]:
#Matriz diagonal 
import numpy as np
print("Matriz diagonal A de dimensión 3x3, :")

A= np.array([[11,2,3],[0,1,4],[0,0,2]])
print(A)

#sacamos el determinante
print("El determinante de su matriz es:")
d= np.linalg.det(A)
print(d)

Matriz A de dimensión 3x3, :
[[11  2  3]
 [ 0  1  4]
 [ 0  0  2]]
El determinante de su matriz es:
22.000000000000004


Si una matriz B se obtiene intercambiando dos filas o intercambiando dos columnas de una matriz A entonces det(B) = −det(A)

In [ ]:
 
import numpy as np
print("Matriz A de dimensión 2x2, :")

A= np.array([[11,2,3],[0,1,4],[6,4,2]])
print(A)

#sacamos el determinante de A
print("El determinante de su matriz A es:")
d= np.linalg.det(A)
print(d)
print("Matriz B de dimensión 2x2, :")
B= np.array([[2,11,3],[1,0,4],[4,6,2]])
print(B)

#sacamos el determinante de B
print("El determinante de su matriz B es:")
l= np.linalg.det(B)
print(l)


Matriz A de dimensión 2x2, :
[[11  2  3]
 [ 0  1  4]
 [ 6  4  2]]
El determinante de su matriz A es:
-124.00000000000003
Matriz B de dimensión 2x2, :
[[ 2 11  3]
 [ 1  0  4]
 [ 4  6  2]]
El determinante de su matriz B es:
123.99999999999991


Si A y B son matrices diagonales de nxn, entonces det AB=det A det B. 

Si A y B son matrices triangulares inferiores, entonces AB=det A det B. 

In [ ]:
import numpy as np
#primero pedimos que se nos den las matrices 
print("recuerde que deben ser matrices cuadradas y diagonales")
filas1 = int(input ("Indique el número de filas y columnas de la matriz: "))


#creamos las matrices en las que se guardarán los valores que el usuario proporcione y los de la suma
A = np.zeros((filas1,filas1))    
B = np.zeros((filas1,filas1))   
 #llenamos la matriz 1 con los datos del usuario
print ("Ingrese la primer matriz")

for i in range(filas1):
        for j in range(filas1):
            A[i][j] = float(input('Elemento (%d,%d): ' % (i, j)))
print( "su matriz 1 es:")
print(A)
#llenamos la matriz 2
print ("Ingrese la segunda matriz")
for i in range(filas1):
        for j in range(filas1):
            B[i][j] = float(input('Elemento (%d,%d): ' % (i, j)))
print( "su matriz 2 es:")
print(B)


C = A.dot(B)
print("El producto de las matrices es:")
    
print (C)

print("El determinante de su matriz A es:")
m= np.linalg.det(A)
print(m)

print("El determinante de su matriz B es:")
n= np.linalg.det(B)
print(n)

print("El determinante de su matriz A*B es:")
l= np.linalg.det(C)
print(l)


recuerde que deben ser matrices cuadradas y diagonales
Indique el número de filas y columnas de la matriz: 2
Ingrese la primer matriz
Elemento (0,0): 2
Elemento (0,1): 3
Elemento (1,0): 0
Elemento (1,1): 3
su matriz 1 es:
[[2. 3.]
 [0. 3.]]
Ingrese la segunda matriz
Elemento (0,0): 3
Elemento (0,1): 4
Elemento (1,0): 0
Elemento (1,1): 3
su matriz 2 es:
[[3. 4.]
 [0. 3.]]
El producto de las matrices es:
[[ 6. 17.]
 [ 0.  9.]]
El determinante de su matriz A es:
6.0
El determinante de su matriz B es:
9.000000000000002
El determinante de su matriz A*B es:
54.00000000000001


No se cumple en general que el det (A + B)=det A + det B

In [ ]:

import numpy as np

A= np.array([[11,2],[0,1]])
print(A)

#sacamos el determinante
print("El determinante de su matriz es:")
d= np.linalg.det(A)
print(d)

S= np.array([[23,12],[11,3]])
print(S)

#sacamos el determinante
print("El determinante de su matriz es:")
m= np.linalg.det(S)
print(m)

print("La suma de las matrices es:")
T=A+S

print("El determinante de su matriz suma es:")
o= np.linalg.det(T)
print(o)

[[11  2]
 [ 0  1]]
El determinante de su matriz es:
11.000000000000002
[[23 12]
 [11  3]]
El determinante de su matriz es:
-62.99999999999999
La suma de las matrices es:
El determinante de su matriz suma es:
-17.999999999999996


Si dos filas (columnas) de A son iguales, entonces det(A) = 0

In [ ]:
S= np.array([[23,12],[23,12]])
print(S)

#sacamos el determinante
print("El determinante de su matriz es:")
m= np.linalg.det(S)
print(m)

[[23 12]
 [23 12]]
El determinante de su matriz es:
0.0


El determinante de una matriz con un escalar es el escalar por el determinante de la matriz, es decir:

Si C= $\tau$*$A_{nxn}$ ,  
entonces det(C)= $\tau$ * det($A_{nxn}$)

Estas son solo algunas de las propiedades que los determinantes poseen.

Fuentes que se consultaron y quedan como sugerencia al lector: 

+ Kolman, B., & Hill, D. R. (2006). Álgebra Lineal. México: Pearson.

+ S., S. I., & Godoy, J. J. (2012). Álgebra Lineal. México: McGrawll -Hill Companies.