<a href="https://colab.research.google.com/github/jugernaut/Prometeo/blob/desarrollo/02_AlgebraLineal/04_EigenvaloresyEigenvectores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Eigenvalores y Eigenvectores
## Proyecto PAPIME PE101019
- Autor: Ortega Ibarra Jaime
- Rev: 31 Julio 2020

### **Eigenvectores**
\
En álgebra lineal, los vectores propios o autovectores de un operador lineal son los vectores no nulos que, cuando son transformados por el operador, dan lugar a un múltiplo escalar de sí mismos, con lo que no cambian su dirección. Este escalar $\lambda$  recibe el nombre valor propio, autovalor o valor característico.\
\
Definición:\
\
Formalmente, se definen los vectores propios y valores propios de la siguiente manera: Sea $A: V→V$ un operador lineal en un cierto $K$-espacio vectorial $V$ y $v$ un vector no nulo en $V$. Si existe un escalar $c$ tal que

\begin{equation}
Av = cv,    v\neq0, c\in K
\end{equation}

Valores y Vectores propios, mediante la función linalg de $Numpy$, podemos obtener un vector que incluye los valores propios de una matriz, además de una matriz con los vectores propios.

In [ ]:
from numpy import linalg
import numpy as np
Matriz = np.array([[1,3,2],[4,1,2],[3,-1,3]])
eigenvals, eigenvectores = linalg.eig(Matriz)
print(f'Nuestro vector con valores propios es: \n{eigenvals}')

Nuestro vector con valores propios es: 
[-2.57358059  5.74856519  1.82501539]


### **Eigenvalores**
\
Sea $A$ es una matriz cuadrada. Un eigenvalues (valor propio) de dicha matriz $A$ es un número $r$ que cuando se resta de cada una de las entradas diagonales de $A$, se convierte $A$ en una matriz singular. Restar un escalar $r$ de cada entrada diagonal de $A$ es lo mismo que restar $r$ veces la matriz identidad $I$ de $A$.

Por lo tanto, $r$ es un valor propio de $A$ si y solo si $A-rI$ es una matriz singular.

Ejemplo:

Matriz $A$

\begin{equation}
A = \begin{matrix} 5, 1, 1 \\ 1, 5, 1 \\ 1, 1, 5 \end{matrix}
\end{equation}

Al restar $4$ de cada entrada diagonal se transforma $A$ en la matriz singular

\begin{equation}
A = \begin{matrix} 1, 1, 1 \\ 1, 1, 1 \\ 1, 1, 1 \end{matrix}
\end{equation}

Por lo tanto, $4$ es un valor propio de $A$.

Dado el ejemplo anterior mediante $Numpy$, podemos obtener los valores propios de la Matriz creada.

In [ ]:
print(f'\nNuestra matriz con los vectores propios es: \n{eigenvectores}')


Nuestra matriz con los vectores propios es: 
[[ 0.70643716 -0.60432967 -0.45736161]
 [-0.52518953 -0.68232213 -0.57693279]
 [-0.47447076 -0.41136622  0.676734  ]]
