<a href="https://colab.research.google.com/github/jugernaut/Prometeo/blob/desarrollo/02_AlgebraLineal/04_EigenvaloresyEigenvectores/04_EigenvaloresyEigenvectores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Eigenvalores y Eigenvectores

### Trabajo realizado con el apoyo del Programa UNAM-DGAPA-PAPIME PE101019

*   Autor: 
  - Jaime Jesús Ortega Ibarra
*   Rev: jueves nov 19 13:41:39 CDT 2020

## Introducción
Los Eigenvalores y Eigenvectores son conceptos sumamente empleados en diferentes áreas de las matemáticas aplicadas e ingenierías. La raíz $eigen$ proviene del alemán y significa $propio$, por lo cual podemos definir como Valores propios o valores característicos de una transformación lineal o de una matriz, mientras los eigenvectores pueden ser definidos como vectores propios o vectores característicos de una transformación lineal o de una matriz.

### Definición

Sea $V$ un espacio vectorial sobre un campo $K$ y sea $T$ una transformación lineal

$$T:V \rightarrow V$$

un vector $\vec{v_{0}}$ $\ne$ 0 del espacio vectorial $V$ se denomina un eigenvector de T si existe un escalar $\lambda$ $\in$ $K$ tal que

$$T(\vec v_{0})= \lambda \vec v_{0},$$

en este caso $\lambda \in K$ se denomina el eigenvalor de la transformación $T$ asociado al eigenvector $\vec v_{0}$

De manera semejante podemos definir los eigenvectores y eigenvalores de una matriz M.

Sea $M \in K_{nxn}$ para algún número natural n, un elemento $\vec{x} \in K_{n}$ se denomina un eigenvector de $M$ si existe un escalar $\lambda \in K$ tal que

$$M \vec{x} = \lambda \vec{x}$$

en este caso $\lambda \in K$ se denomna eigenvalor de la matriz $M$ asociado al eigenvector $\vec{x}$.
 


### Ejemplo:
Dada una matriz:
\begin{equation}
A = \begin{bmatrix} -1, 3 \\ 2, 4 \end{bmatrix}
\end{equation}
Obtener sus Eigenvalores.

Se debe obtener la determinante de la matriz, restandole a la diagonal el parámetro $\lambda$, es decir:
\begin{equation}
detA = \begin{bmatrix} -1 - \lambda,  3 \\ 2, 4 - \lambda \end{bmatrix} = (-1 - \lambda) (4 - \lambda) - 6 = 0
\end{equation}
Desarrollando el producto de binomios
\begin{equation}
-4 + \lambda - 4 \lambda + \lambda ^2 -6 
\end{equation}
\begin{equation}
= \lambda ^2 - 3 \lambda -10 = 0
\end{equation}
Lo cual factorizando, nos da lo siguiente
\begin{equation}
= (\lambda +2) (\lambda -5)
\end{equation}
$\therefore$ Nuestros eigenvalores son:
\begin{equation}
\lambda_{1} = -2 
\end{equation}
\begin{equation}
\lambda_{2} = 5
\end{equation}

Dentro del lenguaje de programación $Python$ podemos obtener Valores y Vectores propios, mediante la función linalg de $Numpy$, es decir, podemos obtener un vector que incluye los valores propios de una matriz, además de una matriz con los vectores propios.

In [ ]:
# Importamos las librerías necesarias

from numpy import linalg
import numpy as np

# Creamos nuestra matriz mediante numpy.array
Matriz = np.array([[1,3,2],[4,1,2],[3,-1,3]])

#Obtenemos nuestros valores y vectores propios mediante la función linalg.eig()
#Almacenamos lo obtenido de la función en las variables eigenvalores y eigenvectores
eigenvalores, eigenvectores = linalg.eig(Matriz)

#Imprimimos nuestros valores propios
print(f'Nuestro vector con eigenvalores es: \n{eigenvalores}')

Nuestro vector con eigenvalores es: 
[-2.57358059  5.74856519  1.82501539]


### Ejemplo:

Sea $A$ es una matriz cuadrada. Un eigenvalor de dicha matriz $A$ es un número $r$ que cuando se resta de cada una de las entradas diagonales de $A$, se convierte $A$ en una matriz singular. Restar un escalar $r$ de cada entrada diagonal de $A$ es lo mismo que restar $r$ veces la matriz identidad $I$ de $A$.

Por lo tanto, $r$ es un valor propio de $A$ si y solo si $A-rI$ es una matriz singular.

Matriz $A$
\begin{equation}
A = \begin{bmatrix}  5, 1, 1 \\ 1, 5, 1 \\ 1, 1, 5 \end{bmatrix}
\end{equation}


Al restar $4$ de cada entrada diagonal se transforma $A$ en la matriz singular

\begin{equation}
A = \begin{bmatrix}  1, 1, 1 \\ 1, 1, 1 \\ 1, 1, 1 \end{bmatrix}
\end{equation}


Por lo tanto, $4$ es un valor propio de $A$.

Dado el ejemplo anterior, de igual manera mediante $Numpy$ podemos obtener los valores propios de la Matriz anteriormente creada.

In [ ]:
# Imprimimos nuestro vector propio
print(f'\nNuestra matriz con los eigenvectores es: \n{eigenvectores}')


Nuestra matriz con los eigenvectores es: 
[[ 0.70643716 -0.60432967 -0.45736161]
 [-0.52518953 -0.68232213 -0.57693279]
 [-0.47447076 -0.41136622  0.676734  ]]


Para mayor información, se recomienda al lector consultar los siguientes sitios:
- https://www.cimat.mx/~joaquin/mn11/clase11.pdf
- https://sites.google.com/site/metalmetnumericos/home/unidad-3/3-7-obtencion-de-eigenvalores-y-eigenvectores
- https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html

#Evalúa tu conocimiento 

Si deseas contestar un breve cuestionario en el que podras evaluar un poco del conocimiento aquirido en este notebook da clic en el siguiente enlace:

https://docs.google.com/forms/d/11fK3qrX2wmTj8PM3bqDGDat3A3p_ZPKY83E6Oanrk_g/edit